redis client in go
CodingChallengesFYI/SharedSolutions pull request #332
Opened 2024-07-27 14:12 UTC by Re1nGer

It's a golang redis client but not a cli tool, I started out from building redis server [challenge](https://codingchallenges.fyi/challenges/challenge-redis) and decided to build the client for testing it, eventually I stuck with a client and not a server, the closest challenge in the list is building [redis-cli-tool ](https://codingchallenges.fyi/challenges/challenge-redis-cli) 

I understand that it may not quite fit the description of expected solution, so I'm okay closing this PR in this case

2024-08-19 17:23 UTC, JohnCrickett commented
Thanks it's a great starting point for someone else to use to build the CLI tool.

2024-08-19 17:24 UTC, JohnCrickett requested changes
Should link this from the main README.md

It.s not quite a solution, but might be cool to list as a Go client that others can use?

2024-08-20 10:24 UTC, Re1nGer commented
> Should link this from the main README.md 

I updated MR and currently it's listed as Redis CLI tool 

> It.s not quite a solution, but might be cool to list as a Go client that others can use? 

Should I list it as a Redis Go Client ?

2024-10-04 07:46 UTC, JohnCrickett approved these changes

2024-10-04 07:47 UTC, merged